### ISSUE TITLE
Build out mini-admin panel

### ISSUE THREAD

**Issue by MelissaAutumn** [thunderbird/appointment#362]
For alpha we'll need an admin panel to manage invite code generation, and maybe user lookup/disable. 

We can just use the default tailwind table styling:
https://tailwindcss.com/docs/table-layout

We'll need a few endpoints: 
 * [x] Query all invites
 * [x] Generate `n` invites
 * [x] Revoke a specific invite
 
 (Maybe out of scope for alpha):
 * List all subscribers (data limited to id, username, invite code used (or None), date created)
 * Disable a specific subscriber

Admin panel is gated via a custom middleware check on the backend and some hard coded strings on the frontend. So if someone really wanted to look at the admin panel they probably could, but the backend function would prevent any of the functionality (like showing, or performing actions) from working. 

We can fine-tune our database models later...

**Comment by devmount** [comment]
As presented today, I did some UI improvements, added a pagination component and the revokal of invite codes, available under `/admin/invites`

![image](https://github.com/thunderbird/appointment/assets/5441654/f7fb8317-acb6-4340-af23-45a3774ee6da)

What are next steps? Should I add a simple overview of subscribers under `/admin/users`? Anything else needed for this ticket?

**Comment by MelissaAutumn** [comment]
Thanks! Users would be good! 

We also need a custom middleware for these routes that reads off an allow list like how we implement the fxa allow list (see the `FXA_ALLOW_LIST` env variable.)

**Comment by devmount** [comment]
Ok I might need some additional inspiration here 🙈 I thought this would be easy doable with a custom HTTPMiddleware like this:

```python
import os

from fastapi import Depends, HTTPException, Request
from starlette.middleware.base import BaseHTTPMiddleware
from ..dependencies.auth import get_subscriber

class PermissionMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        subscriber = Depends(get_subscriber)
        ALLOW_LIST = os.getenv("APP_ADMIN_ALLOW_LIST", '').split(',')
        if not subscriber.email in ALLOW_LIST:
            raise HTTPException(status_code=403, detail="Insufficient permissions")
        return await call_next(request)
```

But turns out that at this point, I cannot simple retrieve the currently logged in user from our auth module, right? I somehow need to get it from the request itself, which feels like doing everything from the auth module again.

On the other hand, there seems to be a [convenient decorator from starlette](https://www.starlette.io/authentication/#permissions), which is as easy as `@requires('admin')` 😍 But for that we need to build our own AuthenticationBackend.

@MelissaAutumn Maybe you see a solution here without reqriting our whole auth module? 😅

**Comment by devmount** [comment]
Good thinking, thank you. Will give that a try 👍🏻

**Comment by MelissaAutumn** [comment]
For the purposes of the alpha, we can skip the user section and just roll this out once the admin dependency is implemented.

**Comment by devmount** [comment]
Alright, it isn't as beautiful as a middleware, but it worked just fine that way. For all admin user protected routes, we have to add a `admin: Subscriber = Depends(get_admin_subscriber)` as function parameter 👍🏻
