### ISSUE TITLE
Filter profanity/etc from public user names/urls

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#574]
**Is your feature request related to a problem? Please describe.**
We do not filter user's shortUrls and we should check them against a list of known profanity/etc, so we do not allow harmful language.

**Describe the solution you'd like**
Determine if Mozilla maintains a profanity filter somewhere we can leverage, or find a suitable alternative (maybe https://github.com/coffee-and-fun/google-profanity-words ?

When users select their username/shortUrls/etc, we should run their input through the filter before accepting it.

**Comment by malini** [comment]
i put it as beta v2 because it would be best to have this before we have non-mozillian users

**Comment by devmount** [comment]
I analyzed the code base and found the following place where a profanity filter might make sense:

- `/dashboard`: schedule name
- `/settings/account`: username, display name
- `/setup` (FTUE): full name, username, schedule name

@malini Are those places enough for beta for now? Is a frontend filter sufficient for now?

**Comment by devmount** [comment]
Ok this was more pain than expected 😅  How hard can it be to create a working lib that provides filtering against a fixed set of words 🙈 

- [coffee-and-fun/google-profanity-words](https://github.com/coffee-and-fun/google-profanity-words) Is not typed and throws errors on execution
- [2Toad/Profanity](https://github.com/2Toad/Profanity) is typed and actively maintained, but only supports the English language
- [Gabriel-Ciriaco/super-profanity](https://github.com/Gabriel-Ciriaco/super-profanity) is MPL licensed and supports 27 different languages, but is not typed and throws errors on import

So I went with the 2nd one for now, since it was the only one that worked anyway. If we find another more suitable lib that contains other languages as well, we can easily switch.

![image](https://github.com/user-attachments/assets/2e87a6d3-553c-465c-b6b6-c8b187516d8a)
![image](https://github.com/user-attachments/assets/f1791e43-a74b-482e-bba0-794672161e41)
![image](https://github.com/user-attachments/assets/97ee476f-b26f-4a81-b560-8fa9f9543494)
![profanity1](https://github.com/user-attachments/assets/99a0f22c-7913-4b86-951a-b00a035958df)
![profanity2](https://github.com/user-attachments/assets/a65c23f8-b33b-4c60-ade4-378e2a8bb1f7)

**Comment by devmount** [comment]
Good news: The maintainer of https://github.com/2Toad/Profanity is quite active and directly responded to [my feature request](https://github.com/2Toad/Profanity/issues/87) for multiple languages. So we might just keep that for now.

**Comment by nroach44** [comment]
This is, perhaps well intentioned, but inappropriate.

People's names may have "offensive" terms in them, not only in their native language (see Cox, Cockburn, Dick) or in other languages.

I would strongly recommend reverting this altogether.

See:

https://fosstodon.org/@kevincox/113902339496383352

https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/ point 31, specifically:

> I can safely assume that this dictionary of bad words contains no people’s names in it.

**Comment by malini** [comment]
Yes, thanks for the reports. As mentioned, this was well-intentioned, but ultimately not a feature we can adequately maintain by a team of our small size. We'll remove the profanity filter, and rely on support requests if people suspect misuse. We've filed https://github.com/thunderbird/appointment/issues/840 to remove the filter
