### ISSUE TITLE
Update emailed booking request UI

### ISSUE THREAD

**Issue by malini** [thunderbird/appointment#612]
**Is your feature request related to a problem? Please describe.**
We have an updated UI for the booking request email that goes out: [Figma](https://www.figma.com/file/U6AtC6P44lvaa6L8sWWjxP?node-id=4503%3A10396&type=design&fuid=1334275840754758209#879708402) and we should implement it ideally before public beta invite codes go out.

**Comment by MelissaAutumn** [comment]
Thunderbird:
<img width="638" alt="image" src="https://github.com/user-attachments/assets/f23d1d9f-8b3b-49ee-97ba-1ac68da277f0">

Gmail:
<img width="462" alt="image" src="https://github.com/user-attachments/assets/f73ff3e1-c409-4c62-a17b-e87b4ee2aa2d">

Gmail added a little "Click to expand" because it started batching my test emails as a conversation :I

I spent some time creating an email template so we more easily swap emails over. So I'm also going through and touching up the other emails, mainly the invitation email which is now based off the confirmation email:

Thunderbird:
<img width="639" alt="image" src="https://github.com/user-attachments/assets/f9c74e80-7c2a-4242-bc01-40441be5bd6d">


Gmail:
<img width="1407" alt="image" src="https://github.com/user-attachments/assets/0fdcac0b-80b3-4bae-a5de-07d7e39d2419">

The rest will just be placed right into the template without much of an adjustment.

**Comment by MelissaAutumn** [comment]
Updated the "No confirmation, alert email" for a schedule owner:
<img width="1354" alt="image" src="https://github.com/user-attachments/assets/ebfbf6dc-81f7-4dd2-a938-252d04357eb5">

The rest of the emails are also on the new template but are unchanged otherwise.

**Comment by MelissaAutumn** [comment]
cc @laurelterlesky @malini 

The emails are on stage for testing!
https://stage.appointment.day/

Test points:
* Login -> Non-waiting list / subscriber email -> Waiting List 
* Booking Page -> Book an Appointment -> (Owner) Confirm this booking email / (Attendee) Awaiting Confirmation Email
* Booking Confirmed -> (Attendee) Your booking was confirmed
* Booking Rejected -> (Attendee) Your booking was rejected
* Booking Page (With Booking Confirmation Off) -> Book an Appointment -> (Owner) You have a new booking / (Attendee) Your booking was confirmed
* Logged in -> Avatar dropdown -> Contact Support -> New Support Request (This goes to a fixed email fyi)
* Admin -> Subscribers -> Invite user (at footer) -> You've been invited to Appointment

**Comment by MelissaAutumn** [comment]
Also @devmount (When you're back!) I've updated the strings the best I can, but I've missed a few and patched a few with google translate 🙀. Just fyi!

**Comment by MelissaAutumn** [comment]
This is live on production now, and all the test points seemingly work. So feel free to close it when the localization is updated!

**Comment by laurelterlesky** [comment]
@MelissaAutumn Can we add a comma between day and year? Example: Tuesday, March 16, 2024?

(I'll correct the designs too)

**Comment by devmount** [comment]
@laurelterlesky Yes, since we already have localized date formats, this is no problem at all. I added the comma between day and year for the English locale in #617.

**Comment by malini** [comment]
I just tested the functionality of the changes and they're working perfectly and look great!

**Comment by malini** [comment]
localization has been merged, closing.
