### ISSUE TITLE
"Have an invite code" is confusing when you only need to enter an email

### ISSUE THREAD

**Issue by kewisch** [thunderbird/appointment#693]
**To Reproduce**

1. Go to appointment.day
2. Click on Sign up for the beta
3. See text

**Expected behavior**
The heading talks about exciting reasons why people should really enter their email and continue and what they are about to experience.

**Actual behavior**
It says "Have an invite code? Enter it here", which is confusing if you can only enter an email

**Screenshots**
![image](https://github.com/user-attachments/assets/eabba186-eb74-4653-bf5f-94099a98c37f)

**Comment by kewisch** [comment]
Also, while we're at it, "Your privacy is important to us" isn't really meaningful as it is. Should this be linking to the privacy policy? 

The only way to escape that dialog is to click "Plan less, do more". This might be on purpose if you want to capture people right there, but the usual pressing escape or clicking outside the dialog don't work for me.

**Comment by devmount** [comment]
Good catches and great suggestions, thank you Philipp! We'll look into that.

@inattee What would be a good copy here? "Have an invite code? First enter your email here"?

@MelissaAutumn I'm wondering why the input field for the actual invitation code is missing at that point 😅 Does it appear when entering the email address?

**Comment by inattee** [comment]
Yes good catch! I'll see what Mel decides about including the invite code field and proceed with the copy for this page.  I'd also love to spruce up the invite email with some excitement while we're at it! :)

**Comment by MelissaAutumn** [comment]
I'm good with adding an x in the corner to dismiss this modal (aka return to home) but I'll just ping @laurelterlesky for a quick check.

And the header part is a bug it seems. Oops.

**Comment by inattee** [comment]
@MelissaAutumn can you confirm what the input field(s) on that modal should be? Then I can make some copy suggestions for it. 

ps. I would add in addition to an x in the corner to close, clicking in the grey area outside the modal is always intuitive for closing it

**Comment by laurelterlesky** [comment]
I can see from Mel's response that some of the issues here are due to a bug. 

The design file is located here: https://www.figma.com/design/L7WgGR3JfGJ6tzFOY1oKdJ/TBA_2024_Q2_Sign-Up?node-id=4503-10396&t=NjWgyOhzAJHy6Elg-1

(which includes the email that is sent when a person signed up)

Please include a dismiss button in  the top right corner (Feel free to use the same specs as TB desktop (in the actions section here: https://www.figma.com/design/1wGTkoIgRfyEbLeiW1XeIx/Design-System--%3E-Components?node-id=1-6&t=KmrMykbhmAKNqZaJ-1)

Clicking outside the modal should also dismiss it the modal and take the user back to the landing page

**Comment by laurelterlesky** [comment]
Update to the first screen of FTUE:

Note: dismiss btn, revised copy, revised spacing

![TBA-SignUp-01-Email](https://github.com/user-attachments/assets/7aeae9d6-9215-4d62-ba47-83fdc5d3bb0a)

Figma link: https://www.figma.com/design/L7WgGR3JfGJ6tzFOY1oKdJ/TBA_2024_Q2_Sign-Up?node-id=6319-915&t=9IZd7H56sU9KQXju-1
