### ISSUE TITLE
Cut down text on log in form

### ISSUE THREAD

**Issue by Sancus** [thunderbird/appointment#699]
![image](https://github.com/user-attachments/assets/8fc99370-0b28-4274-a54e-22b12645cf3d)

This whole form is unnecessarily wordy. I think we can eliminate most of the text here and just rely on the label, so something like this:

![image](https://github.com/user-attachments/assets/c3c6386b-35ac-48bc-9b2d-bc15debf9b0c)

Also, I think this is covered in the other issue about these dialogs, but popups of this type should *always* have an "X" in the top right to close them.

**Comment by MelissaAutumn** [comment]
cc @laurelterlesky & @inattee

**Comment by inattee** [comment]
Looks good to me

**Comment by laurelterlesky** [comment]
It's a bit lengthy for an input field label (especially for screen readers) ... but at least clear and descriptive.

Might be better to a title or H2:
Sign in or create an account

And then the label to be more specific to the input: Email:

This should tighten it up and make it better for screen readers and for users doing pinch and zoom.

Also, can you ensure

**Comment by laurelterlesky** [comment]
Sorry Mel. Had to think on this a bit during my walk w/Echo. We kinda lost the consistency, tone and the brand strategy attempt.

Maybe let's simplify it - and keep it consistent with the rest of the SIgn up beta & FTUE (meaning that the directions are in the H1, and we'll drop the brand strategy since we have a touch in the footer). This will like save it for translations too:

H1: Sign in or create an account

Input field:
label: email address
helper text: We'll never share your email


Input field something like this: 
<label for="email">Email address</label>
<input type="email" id="email" aria-describedby="email-helper" />

<small id="email-helper">We'll never share your email.</small>

**Comment by MelissaAutumn** [comment]
No worries, the never share your email line technically isn't true as we do add it to the calendar files. 

Could we maybe drop the help text or does that make it too bare?

**Comment by laurelterlesky** [comment]
Fair enough. The aim was to make use of our values - but tie it to the input field. 

I'm ok to drop the helper text since it's a bit too disparate to the task. (The error msg will still how there... I might need to increase the font size but that's a future problem)

**Comment by MelissaAutumn** [comment]
So like:
<img width="774" alt="image" src="https://github.com/user-attachments/assets/89d589a9-27e9-4823-8137-1ba6180dfe93">

Or without the logo?

**Comment by laurelterlesky** [comment]
That's perfect and matches the design file too. (I updated it)

**Comment by MelissaAutumn** [comment]
This is live!
